function(add_to_filters items)
	foreach(item IN LISTS ${items})
		get_filename_component(item_path "${item}" PATH)
		string(REPLACE "/" "\\" item_path_win "${item_path}")
		source_group("${item_path_win}" FILES "${item}")
	endforeach()
endfunction()
