set(
	headers
	include/utils/Assert.hpp
	include/utils/EnumUtils.hpp
	include/utils/exceptions/LoggingException.hpp
	include/utils/exceptions/ParseErrorException.hpp
	include/utils/LogDefs.hpp
	include/utils/Logger.hpp
	include/utils/save_restore/StreamReader.hpp
	include/utils/save_restore/StreamWriter.hpp
	include/utils/Singleton.hpp
)