set(
	shaders
	res/shaders/Effects/CommonForEffects.vs
	res/shaders/NormalShader.vs
	res/shaders/ReflectionShader.vs
	res/shaders/SimpleColor.vs
	res/shaders/SimpleTexture.vs
	res/shaders/SkyBoxShader.vs
	res/shaders/TerrainShader.vs
	res/shaders/TriangleShader.vs
	res/shaders/UVdisplacementShader.vs
	res/shaders/WaterShader.vs
	res/shaders/Effects/Blur.fs
	res/shaders/Effects/BW.fs
	res/shaders/Effects/DoF.fs
	res/shaders/Effects/DoFBlur.fs
	res/shaders/Effects/PostBloom.fs
	res/shaders/Effects/PreBloom.fs
	res/shaders/NormalShader.fs
	res/shaders/ReflectionShader.fs
	res/shaders/SimpleColor.fs
	res/shaders/SimpleTexture.fs
	res/shaders/SkyBoxShader.fs
	res/shaders/TerrainShader.fs
	res/shaders/TriangleShader.fs
	res/shaders/UVdisplacementShader.fs
	res/shaders/WaterShader.fs
)