set(
	headers
	include/renderer/common/Axis.hpp
	include/renderer/common/Globals.hpp
	include/renderer/common/Types.hpp
	include/renderer/common/Vertex.hpp
	include/renderer/effects/Effect.hpp
	include/renderer/effects/Pass.hpp
	include/renderer/gl_primitives/Buffer.hpp
	include/renderer/gl_primitives/CubeTexture.hpp
	include/renderer/gl_primitives/Fbo.hpp
	include/renderer/gl_primitives/Texture.hpp
	include/renderer/gl_primitives/TextureBase.hpp
	include/renderer/gl_primitives/TextureFilteringMode.hpp
	include/renderer/gl_primitives/TextureTiling.hpp
	include/renderer/gl_primitives/VertexArray.hpp
	include/renderer/gl_primitives/VertexBufferLayout.hpp
	include/renderer/loaders/ModelsFactory.hpp
	include/renderer/loaders/TexturesFactory.hpp
	include/renderer/managers/EffectManager.hpp
	include/renderer/managers/InputManager.hpp
	include/renderer/managers/ResourceManager.hpp
	include/renderer/managers/SceneManager.hpp
	include/renderer/Renderer.hpp
	include/renderer/scene/AmbientLightData.hpp
	include/renderer/scene/Camera.hpp
	include/renderer/scene/FogData.hpp
	include/renderer/scene/Light.hpp
	include/renderer/scene/Model.hpp
	include/renderer/scene/Object.hpp
	include/renderer/scene/ObjectParameters.hpp
	include/renderer/shaders/Shader.hpp
	include/renderer/shaders/ShaderAttributes.hpp
	include/renderer/shaders/ShaderUniforms.hpp
	src/loaders/formats/LoadTga.hpp
)