set(
	sources
	src/common/Globals.cpp
	src/effects/Effect.cpp
	src/effects/Pass.cpp
	src/gl_primitives/Buffer.cpp
	src/gl_primitives/CubeTexture.cpp
	src/gl_primitives/Fbo.cpp
	src/gl_primitives/Texture.cpp
	src/gl_primitives/TextureBase.cpp
	src/gl_primitives/VertexArray.cpp
	src/loaders/formats/LoadTga.cpp
	src/loaders/ModelsFactory.cpp
	src/loaders/TexturesFactory.cpp
	src/managers/EffectManager.cpp
	src/managers/InputManager.cpp
	src/managers/ResourceManager.cpp
	src/managers/SceneManager.cpp
	src/Renderer.cpp
	src/scene/Camera.cpp
	src/scene/Light.cpp
	src/scene/Model.cpp
	src/scene/Object.cpp
	src/shaders/Shader.cpp
)